### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hjorthjort** [hjorthjort/cosmos-sdk#2]
- [x]  Deliverable 1: High-level system overview (2020-02-08)
- [x]  Deliverable 2: Staking documentation
    - [x]  Bonding, Unbonding, Unbonded
    - [x]  EndBlock events and waiting UnbondingTime
    - [x] How are jailed validators handled during delegation (what happens if you try to delegate to a jailed validator).
    - [x] Delegation, redelegation and ~~key updates of validators~~
      - [x] Sequence diagram for delegating (module interactions)

- [ ]  Deliverable 3: Distribution documentation
    - [x] ~~EndBlock~~ BeginBlock lazy fee distribution
    - [x] Messages
    - [x]  Hooked state updates

**Comment by hjorthjort** [comment]
Per request from @shahankhatch, skip key validator updates and document how jailed validators are handled during delegation.
